---
- name: Configure | YUM repo
  yum_repository:
    name: logdna
    enabled: yes
    description: LogDNA packages
    baseurl: http://repo.logdna.com/el6/
    gpgcheck: no

- name: Install Package | yum | logdna-agent
  yum:
    state: latest
    name: logdna-agent
