---
- import_tasks: install-redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure | logdna-agent config file
  template:
    src: logdna.conf.j2
    dest: /etc/logdna.conf
  notify: service | logdna-agent | restarted

- name: Configure | service | logdna-agent
  become: true
  service:
    name: logdna-agent
    enabled: yes
    state: started
